config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Clobber sign_up for now so no new users can sign up.
  devise_for :users, path_names: {
    sign_up: ""
  }

  root to: "logs#index"

  namespace :admin do
    resources :users, only: [:index, :show]
  end

  resources :users, only: [:update]
  get "users/settings", action: :edit, controller: "users", as: "edit_user_settings"

  resources :charts, only: [:index]
  resources :stats, only: [:index]

  resources :exercises
  resources :pain_log_quick_form_values, only: [:index, :new, :create, :edit, :update, :destroy]
  post "/create_pain_log_from_quick_form", to: "pain_logs#create_from_quick_form"

  resources :pains, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :body_parts, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :logs, only: [:index]
  resources :exercise_logs
  resources :pain_logs
  resources :pt_session_logs do
    resources :exercise_logs, controller: "pt_session_logs/exercise_logs", only: [:new, :create, :show, :edit, :update, :destroy]
  end

  resources :slit_logs
  post "/quick_log_create", to: "slit_logs#quick_log_create"

  resources :slit_log_reports, only: [:index, :new]
end

app/models/exercise_log.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: exercise_logs
#
#  id                :bigint           not null, primary key
#  burn_rep          :integer
#  burn_set          :integer
#  occurred_at       :datetime
#  per_side          :boolean          default(FALSE)
#  progress_note     :text             default("")
#  rep_length        :integer          default(0)
#  reps              :integer          default(0)
#  resistance        :string
#  sets              :integer          default(0)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  body_part_id      :bigint
#  exercise_id       :bigint
#  pt_session_log_id :bigint
#  user_id           :bigint
#
# Indexes
#
#  index_exercise_logs_on_body_part_id       (body_part_id)
#  index_exercise_logs_on_exercise_id        (exercise_id)
#  index_exercise_logs_on_occurred_at        (occurred_at)
#  index_exercise_logs_on_pt_session_log_id  (pt_session_log_id)
#  index_exercise_logs_on_user_id            (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (body_part_id => body_parts.id)
#  fk_rails_...  (exercise_id => exercises.id)
#  fk_rails_...  (pt_session_log_id => pt_session_logs.id)
#  fk_rails_...  (user_id => users.id)
#
class ExerciseLog < ApplicationRecord
  extend Log

  belongs_to :user
  belongs_to :exercise
  belongs_to :body_part
  belongs_to :pt_session_log, optional: true

  validates :occurred_at,
    :exercise_id,
    :body_part_id,
    presence: true

  validates :sets,
    :reps,
    :rep_length,
    presence: true,
    numericality: true

  validates :burn_set,
    :burn_rep,
    presence: {on: :update}

  validates :burn_set,
    :burn_rep,
    numericality: {on: :update}

  delegate :name, to: :body_part, prefix: true
  delegate :name, to: :exercise, prefix: true

  scope :at_home, -> { where(pt_session_log_id: nil) }
  scope :at_pt, -> { where.not(pt_session_log_id: nil) }

  class << self
    def minutes_spent_by_day
      output = {}
      all.find_each do |log|
        occurred = log.occurred_at.to_date

        if output[occurred].nil?
          output[occurred] = log.minutes_spent.round(2)
        else
          output[occurred] += log.minutes_spent.round(2)
        end
      end
      output.sort.to_h
    end
  end

  def seconds_spent
    side_multiplier = per_side ? 2 : 1
    sets * reps * rep_length * side_multiplier
  end

  def minutes_spent
    (seconds_spent.to_f / 60)
  end

  def blank_stats?
    sets.blank? || reps.blank?
  end
end

app/controllers/exercise_logs_controller.rb
# frozen_string_literal: true

class ExerciseLogsController < ApplicationController
  before_action :set_exercise_log, only: %i[show edit update destroy]
  before_action :authorize_exercise_log, only: %i[show edit update destroy]
  layout "no_white_container", only: [:index]

  def index
    logs = current_user.exercise_logs
      .at_home
      .order(occurred_at: "DESC")
      .paginate(page: params[:page], per_page: 25)

    @logs = ExerciseLogDecorator.decorate_collection(logs)
  end

  def show
    @pt_session_log = nil
  end

  def new
    @exercise_log = current_user.exercise_logs.new.decorate
  end

  def edit
  end

  def create
    @exercise_log = current_user.exercise_logs.new(exercise_log_params)

    respond_to do |format|
      if @exercise_log.save
        format.html { redirect_to exercise_log_path(@exercise_log) }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @exercise_log.update(exercise_log_params)
        format.html { redirect_to exercise_log_path(@exercise_log) }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @exercise_log.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
    end
  end

  private

  def authorize_exercise_log
    redirect_to root_path, alert: authorization_alert unless authorized_user?(@exercise_log)
  end

  def set_exercise_log
    @exercise_log = ExerciseLog.find(params[:id]).decorate
  end

  def exercise_log_params
    params.require(:exercise_log).permit(
      :user_id,
      :body_part_id,
      :occurred_at,
      :exercise_id,
      :sets,
      :reps,
      :rep_length,
      :per_side,
      :resistance,
      :burn_set,
      :burn_rep,
      :progress_note
    )
  end
end

app/controllers/pt_session_logs/exercise_logs_controller.rb
# frozen_string_literal: true

class PtSessionLogs::ExerciseLogsController < PtSessionLogsController
  before_action :set_pt_session_log
  before_action :set_exercise_log, only: %i[show edit update destroy]
  before_action :authorize_pt_session_log, only: %i[show edit update destroy]
  before_action :authorize_exercise_log, only: %i[show edit update destroy]
  layout "no_white_container", only: [:index]

  def new
    @exercise_log = @pt_session_log.exercise_logs.new
  end

  def edit
  end

  def show
    render "exercise_logs/show"
  end

  def create
    @exercise_log = @pt_session_log.exercise_logs.new(exercise_log_params)
    @exercise_log.user_id = current_user.id

    respond_to do |format|
      if @exercise_log.save
        format.html { redirect_to pt_session_log_exercise_log_url(@pt_session_log, @exercise_log) }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @exercise_log.update(exercise_log_params)
        format.html { redirect_to pt_session_log_url(@pt_session_log) }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @exercise_log.destroy
    respond_to do |format|
      format.html { redirect_to pt_session_log_path(@pt_session_log), notice: "Exercise log was deleted." }
    end
  end

  private

  def authorize_exercise_log
    redirect_to root_path, alert: authorization_alert unless authorized_user?(@exercise_log)
  end

  def authorize_pt_session_log
    redirect_to root_path, alert: authorization_alert unless authorized_user?(@pt_session_log)
  end

  def set_exercise_log
    @exercise_log = ExerciseLog.find(params[:id]).decorate
  end

  def set_pt_session_log
    @pt_session_log = PtSessionLog.find(params[:pt_session_log_id])
  end

  def exercise_log_params
    params.require(:exercise_log).permit(
      :pt_session_log_id,
      :user_id,
      :body_part_id,
      :occurred_at,
      :exercise_id,
      :sets,
      :reps,
      :rep_length,
      :per_side,
      :resistance,
      :burn_set,
      :burn_rep,
      :progress_note
    )
  end
end

app/helpers/exercise_logs_helper.rb
# frozen_string_literal: true

module ExerciseLogsHelper
  def format_exercise_stats(log)
    per_side = log.per_side ? "each per side" : "each"
    "#{log.sets} sets / #{log.reps} reps at #{log.rep_length} seconds #{per_side}"
  end

  def format_resistance(log)
    " | Resistance: #{log.resistance}. " if log.resistance.present?
  end

  def destination_url(exercise_log, pt_session_log = nil)
    pt_session_log ? pt_session_log_exercise_log_path(pt_session_log, exercise_log) : exercise_log_path(exercise_log)
  end

  def new_exercise_log_button(pt_session_log)
    if pt_session_log
      link_to '<i class="fal fa-hospital-user"></i> Log Another PT Exercise'.html_safe,
        new_pt_session_log_exercise_log_path(pt_session_log),
        class: "btn btn-outline btn-wide btn-info"
    else
      link_to '<i class="fal fa-dumbbell"></i> Log Another Exercise'.html_safe,
        new_exercise_log_path,
        class: "btn btn-outline btn-wide btn-success"
    end
  end
end

app/views/exercise_logs/_exercise_log.html.erb
<% @log_content = capture do %>
  <h5 class='card-title color-exercise'><%= exercise_log.display_name %>: <%= format_datetime(exercise_log.occurred_at) %></h5>
  <p class="card-text"><strong><%= exercise_log.body_part_name.titleize %>:</strong> <%= exercise_log.exercise_name.titleize %>: <%= format_exercise_stats(exercise_log) %><br>
    <% unless exercise_log.burn_rep.blank? && exercise_log.progress_note.blank? %>
      <small class="text-muted">Progress: exercise burn at Set <%= exercise_log.burn_set %> / Rep <%= exercise_log.burn_rep %>.<%= format_resistance(exercise_log) %> <%= exercise_log.progress_note %></small>
    <% end %>
  </p>
<% end %>

<%= render partial: '/logs/log_component',
  locals: {
    log: exercise_log,
    log_content: @log_content,
    edit_path: edit_exercise_log_path(exercise_log),
    error_condition: false
  }
%>

app/views/exercise_logs/_form.html.erb
<%= form_with(model: exercise_log, url: url) do |form| %>
  <%= render partial: 'shared/errors', locals: {object: exercise_log} %>

  <div class='field'>
    <%= form.label 'Target Body Part', class: 'required' %>
    <%= form.collection_select :body_part_id,
        current_user.body_parts.active.by_name,
        :id,
        :name,
        { prompt: '--Select--' },
        { required: true, class: 'form-control' } %>
  </div>

  <div class='field'>
    <%= render partial: 'shared/datetime_picker', locals: {form: form} %>
  </div>

  <div class='field' data-controller="exercise-defaults">
    <%= form.label 'Exercise', class: 'required' %>
    <%= form.collection_select :exercise_id,
        current_user.exercises.by_name,
        :id,
        :name,
        { prompt: '--Select--' },
        { required: true, class: 'form-control', data: { action: "change->exercise-defaults#change" } } %>
  </div>

  <div class='row'>
    <div class='col'>
      <div class='field'>
        <%= form.label :sets, class: 'required' %>
        <%= form.number_field :sets, required: true, class: 'form-control' %>
      </div>
    </div>

    <div class='col'>
      <div class='field'>
        <%= form.label :reps, class: 'required' %>
        <%= form.number_field :reps, required: true, class: 'form-control' %>
      </div>
    </div>

    <div class='col'>
      <div class='field'>
        <%= form.label :rep_length, class: 'required' %>
        <%= form.number_field :rep_length, required: true, class: 'form-control' %>
      </div>
    </div>

    <div class='col'>
      <div class='field'>
        <%= form.label 'Per Side?' %>
        <%= form.check_box :per_side, class: 'form-control' %>
      </div>
    </div>
  </div> <!-- row -->

  <div class='field'>
    <%= form.label 'Resistance Level' %>
    <%= form.text_field :resistance, class: 'form-control' %>
  </div>

  <div class='row'>
    <div class='col'>
      <div id='burn-set-container' class='field'>
        <%= form.label 'Burn Set #' %>
        <%= form.number_field :burn_set, class: 'form-control' %>
      </div>
    </div>

    <div class='col'>
      <div id='burn-rep-container' class='field'>
        <%= form.label 'Burn Rep #' %>
        <%= form.number_field :burn_rep, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class='field'>
    <%= form.label :progress_note %>
    <%= form.text_area :progress_note, class: 'form-control' %>
  </div>

  <div class='mt-3 mb-3'>
    <%= form.submit class: button_class('success') %>
    <%= link_to 'Cancel', @pt_session_log ? pt_session_log_path(@pt_session_log) : exercise_logs_path, class: button_class('secondary') %>
  </div>
<% end %>

app/views/exercise_logs/_rep_counter_modal.html.erb
<!-- Exercise Rep Counter Modal -->
<%= tag.div id: "repCounterModal", class: "modal fade", tabindex: "1", role: "dialog",
  "aria-labelledby": "repCounterModalLabel",
  "aria-hidden": "true",
  data: {
    controller: "exercise-counter",
    "exercise-counter-sets-value": sets,
    "exercise-counter-reps-value": reps,
    "exercise-counter-rep-length-value": rep_length
  } do %>

  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="repCounterModalLabel">Rep Counter</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Dismiss">
          <span class="modal-dismiss">Close</span>
        </button>
      </div>
      <div class="modal-body">
        <h3>
          <span data-exercise-counter-target="statusIndicator" class='hidden'></span>
        </h3>
        <div class='row'>
          <div class='col'>
            <p class='set-rep-row'>Set:<br>
              <span data-exercise-counter-target="setDisplay" class='counter-number-big'>0</span> of <%= sets %>
            </p>
          </div>
          <div class='col'>
            <p class='set-rep-row'>Rep: (Hold for <%= rep_length %>)<br>
              <span data-exercise-counter-target="repDisplay" class='counter-number-big'>0</span> of <%= reps %><br>
            </p>
          </div>
        </div>

        <%= link_to '#', class: button_class('success'), data: {
              exercise_counter_target: "startButton",
              action: "click->exercise-counter#start"
            } do %>
            <%= MaterialIconComponent.new(icon: "play_arrow", title: "Start Rep Counter", filled: true, size: :medium).render %>
            Start Timer
        <% end %>

        <%= link_to cancel_url, class: button_class('danger pull-right'), data: {
              exercise_counter_target: "stopButton",
              action: "click->exercise-counter#stop"
            } do %>
            <%= MaterialIconComponent.new(icon: "stop", title: "Stop Rep Counter", filled: true, size: :medium).render %>
            Stop & Reset
        <% end %>
      </div><!-- modal body -->
    </div>
  </div>
<% end %>

app/views/exercise_logs/edit.html.erb
<% content_for(:title, format_datetime(@exercise_log.occurred_at)) %>

<%= render partial: 'logs/log_header', locals: { log: @exercise_log } %>

<h2>
  <span class='pull-right'>
    <%= link_to 'Show', @exercise_log, class: button_class %>
    <%= link_to 'Index', exercise_logs_path, class: button_class %>
  </span>
  Editing <%= @exercise_log.exercise_name.titleize %>
</h2>

<%= render 'form', exercise_log: @exercise_log, url: exercise_log_path(@exercise_log) %>

<%= render partial: 'logs/delete_footer', locals: { object: @exercise_log, delete_path: @exercise_log } %>

app/views/exercise_logs/index.html.erb
<header class='add-log-buttons-container'>
  <%= NewLogButtonComponent.new(log_klass: ExerciseLog).render %>
</header>

<% @logs.each do |exercise_log| %>
  <%= render partial: 'exercise_log', locals: { exercise_log: exercise_log } %>
<% end %>
<br>

<%= will_paginate @logs, :page_links => false %>

app/views/exercise_logs/new.html.erb
<%= render partial: 'logs/log_header', locals: { log: @exercise_log } %>

<h1 class='log-h1'>Log an Exercise</h1>

<%= render 'form', exercise_log: @exercise_log, url: exercise_logs_path %>

app/views/exercise_logs/show.html.erb
<% content_for(:title, format_datetime(@exercise_log.occurred_at)) %>

<%= render partial: 'logs/log_header', locals: { log: @exercise_log, style_name: 'exercise', log_name: 'Exercise', icon_name: 'exercise' } %>

<h2>
  <span class='pull-right'>
    <%= link_to 'Edit', @pt_session_log ? edit_pt_session_log_exercise_log_path(@pt_session_log, @exercise_log) : edit_exercise_log_path(@exercise_log), class: button_class %>
    <%= link_to 'Back', @pt_session_log ? pt_session_log_path(@pt_session_log) : logs_path, class: button_class %>
  </span>
  <%= @exercise_log.exercise_name.titleize %>
</h2>

<p>
  <%= format_exercise_stats(@exercise_log) %>
</p>

<p>
  <%= format_datetime(@exercise_log.occurred_at) %>
</p>

<p>
  <strong>Describe 1 Rep:</strong><br>
  <%= @exercise_log.exercise.description %>
</p>

<p>
  <strong>Progress notes:</strong><br>
  For: <%= @exercise_log.body_part_name %> | Burn at Set <%= @exercise_log.burn_set %>, Rep <%= @exercise_log.burn_rep %><%= format_resistance(@exercise_log) %><br>
  <%= @exercise_log.progress_note %>
</p>


<!-- Button trigger modal -->
<button type='button' class='btn btn-warning btn-wide' data-bs-toggle='modal' data-bs-target='#repCounterModal'>
  <i class='far fa-stopwatch'></i> Launch Rep Counter
</button>

<%= render partial: 'exercise_logs/rep_counter_modal', locals: { sets: @exercise_log.sets, reps: @exercise_log.reps, rep_length: @exercise_log.rep_length, cancel_url: destination_url(@exercise_log, @pt_session_log) } %>
<%= new_exercise_log_button(@pt_session_log) %>