config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Clobber sign_up for now so no new users can sign up.
  devise_for :users, path_names: {
    sign_up: ""
  }

  root to: "logs#index"

  namespace :admin do
    resources :users, only: [:index, :show]
  end

  resources :users, only: [:update]
  get "users/settings", action: :edit, controller: "users", as: "edit_user_settings"

  resources :charts, only: [:index]
  resources :stats, only: [:index]

  resources :exercises
  resources :pain_log_quick_form_values, only: [:index, :new, :create, :edit, :update, :destroy]
  post "/create_pain_log_from_quick_form", to: "pain_logs#create_from_quick_form"

  resources :pains, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :body_parts, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :logs, only: [:index]
  resources :exercise_logs
  resources :pain_logs
  resources :pt_session_logs do
    resources :exercise_logs, controller: "pt_session_logs/exercise_logs", only: [:new, :create, :show, :edit, :update, :destroy]
  end

  resources :slit_logs
  post "/quick_log_create", to: "slit_logs#quick_log_create"

  resources :slit_log_reports, only: [:index, :new]
end

app/models/pain_log_quick_form_value.rb
# == Schema Information
#
# Table name: pain_log_quick_form_values
#
#  id               :bigint           not null, primary key
#  name             :string           not null
#  pain_description :text
#  pain_level       :integer
#  trigger          :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  body_part_id     :bigint
#  pain_id          :bigint
#  user_id          :bigint
#
# Indexes
#
#  index_pain_log_quick_form_values_on_body_part_id  (body_part_id)
#  index_pain_log_quick_form_values_on_pain_id       (pain_id)
#  index_pain_log_quick_form_values_on_user_id       (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (body_part_id => body_parts.id)
#  fk_rails_...  (pain_id => pains.id)
#  fk_rails_...  (user_id => users.id)
#

# frozen_string_literal: true

class PainLogQuickFormValue < ApplicationRecord
  extend Sortable
  extend Searchable

  belongs_to :user
  belongs_to :pain
  belongs_to :body_part

  validates :name,
    presence: true,
    uniqueness: {
      case_sensitive: false,
      scope: :user_id
    }

  validates :pain_level,
    presence: true,
    numericality: true

  def loggable_attributes
    attributes
      .except("id", "name", "created_at", "updated_at")
      .merge(occurred_at: Time.current)
  end
end

app/controllers/pain_log_quick_form_values_controller.rb
# frozen_string_literal: true

class PainLogQuickFormValuesController < ApplicationController
  before_action :set_pain_log_quick_form_value, only: %i[edit update destroy]
  before_action :authorize_pain_log_quick_form_value, only: %i[edit update destroy]

  def index
    @pain_log_quick_form_values = current_user.pain_log_quick_form_values
      .search(params[:search])
      .by_name
  end

  def new
    @pain_log_quick_form_value = current_user.pain_log_quick_form_values.new
  end

  def edit
  end

  def create
    @pain_log_quick_form_value = current_user.pain_log_quick_form_values.new(pain_log_quick_form_value_params)

    if @pain_log_quick_form_value.save
      redirect_to pain_log_quick_form_values_url, notice: "#{@pain_log_quick_form_value.name} was created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @pain_log_quick_form_value.update(pain_log_quick_form_value_params)
      redirect_to pain_log_quick_form_values_url, notice: "#{@pain_log_quick_form_value.name} was updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @pain_log_quick_form_value.destroy
    redirect_to pain_log_quick_form_values_url, notice: "#{@pain_log_quick_form_value.name} was deleted."
  end

  private

  def authorize_pain_log_quick_form_value
    redirect_to root_path, alert: authorization_alert unless authorized_user?(@pain_log_quick_form_value)
  end

  def set_pain_log_quick_form_value
    @pain_log_quick_form_value = current_user.pain_log_quick_form_values.find(params[:id])
  end

  def pain_log_quick_form_value_params
    params.require(:pain_log_quick_form_value)
      .permit(:user_id, :body_part_id, :pain_id, :pain_level, :trigger, :pain_description, :name)
  end
end

app/views/pain_log_quick_form_values/_form.html.erb
<%= form_with(model: pain_log_quick_form_value) do |form| %>
  <%= render partial: 'shared/errors', locals: {object: pain_log_quick_form_value} %>

  <div class='field'>
    <%= form.label 'Name', class: 'required' %>
    <%= form.text_field :name, required: true, placeholder: 'ex: Average Tension Headache', class: 'form-control' %>
  </div>

  <div class='field'>
    <%= form.label 'Body Part', class: 'required' %>
    <%= form.collection_select :body_part_id,
        current_user.body_parts.active.by_name,
        :id,
        :name,
        { prompt: '--Select--' },
        required: true,
        class: 'form-control' %>
  </div>

  <div class='row'>
    <div class='col'>
      <div class='field'>
        <%= form.label 'Pain Type', class: 'required' %>
        <%= form.collection_select :pain_id,
            current_user.pains.by_name,
            :id,
            :name,
            { prompt: '--Select--' },
            required: true,
            class: 'form-control' %>
      </div>
    </div>

    <div class='col'>
      <div class='field'>
        <%= form.label 'Pain Level (0 = none, 10 = worst)', class: 'required' %>
        <%= form.number_field :pain_level, required: true, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class='field'>
    <%= form.label 'What were you doing when this happened?' %>
    <%= form.text_area :trigger, class: 'form-control' %>
  </div>

  <div class='field'>
    <%= form.label 'Describe Pain' %>
    <%= form.text_area :pain_description, class: 'form-control' %>
  </div>

  <div class='mt-3 mb-3'>
    <%= form.submit 'Save', class: button_class('success') %>
    <%= link_to 'Cancel', pain_log_quick_form_values_path, class: button_class('secondary') %>
  </div>
<% end %>

app/views/pain_log_quick_form_values/edit.html.erb
<h1>Editing default values for: <%= @pain_log_quick_form_value.name %></h1>
<p>Any changes you make to this data will become the new default values for your quick-logging shortcut. If you want to edit a specific pain experience, go to <%= link_to 'pain logs', pain_logs_path %> and edit the appropriate pain log.</p>
<%= render 'form', pain_log_quick_form_value: @pain_log_quick_form_value %>

app/views/pain_log_quick_form_values/index.html.erb
<%= link_to 'Add a Quick Log Link', new_pain_log_quick_form_value_path, class: button_class('primary pull-right') %>

<h1>Common Pain Quick Log Settings</h1>
<p>Create a one-click link to easily add a pain log for your common pains.</p>

<% if current_user.pain_log_quick_form_values.any? %>
  <%= render partial: 'shared/search_form', locals: { url: pain_log_quick_form_values_path } %>

  <section>
    <% @pain_log_quick_form_values.each do |pain_log_quick_form_value| %>
      <details class='index-list-item'>
        <summary><%= link_to pain_log_quick_form_value.name, edit_pain_log_quick_form_value_path(pain_log_quick_form_value) %></summary>
        <p class='exercise-description'>
          <%= pain_log_quick_form_value.pain.name %> of intensity <%= pain_log_quick_form_value.pain_level %> | <%= pain_log_quick_form_value.body_part.name %>
        </p>
      </details>
    <% end %>
  </section>

<% else %>
  <%= link_to 'Get Started!', new_pain_log_quick_form_value_path, class: button_class('primary btn-wide') %>
<% end %>

app/views/pain_log_quick_form_values/new.html.erb
<h1>Add Quick Log Link</h1>
<p>Add a set of commonly-entered values for a pain you experience regularly. This will create an "easy button" that will allow 1-click logging with these values in a new pain log.</p>

<%= render 'form', pain_log_quick_form_value: @pain_log_quick_form_value %>