config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Clobber sign_up for now so no new users can sign up.
  devise_for :users, path_names: {
    sign_up: ""
  }

  root to: "logs#index"

  namespace :admin do
    resources :users, only: [:index, :show]
  end

  resources :users, only: [:update]
  get "users/settings", action: :edit, controller: "users", as: "edit_user_settings"

  resources :charts, only: [:index]
  resources :stats, only: [:index]

  resources :exercises
  resources :pain_log_quick_form_values, only: [:index, :new, :create, :edit, :update, :destroy]
  post "/create_pain_log_from_quick_form", to: "pain_logs#create_from_quick_form"

  resources :pains, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :body_parts, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :logs, only: [:index]
  resources :exercise_logs
  resources :pain_logs
  resources :pt_session_logs do
    resources :exercise_logs, controller: "pt_session_logs/exercise_logs", only: [:new, :create, :show, :edit, :update, :destroy]
  end

  resources :slit_logs
  post "/quick_log_create", to: "slit_logs#quick_log_create"

  resources :slit_log_reports, only: [:index, :new]
end

app/views/shared/_add_log_buttons.html.erb
<header class='add-log-buttons-container'>
  <%= render partial: 'shared/quick_log_button_to', locals: { text: 'SLIT', decorated_log: SlitLog.new.decorate, path: quick_log_create_path, use_js: true } if current_user.enable_slit_tracking?  %>
  <%= NewLogButtonComponent.new(log_klass: PainLog).render %>
  <%= NewLogButtonComponent.new(log_klass: ExerciseLog).render %>
  <%= NewLogButtonComponent.new(log_klass: PtSessionLog, text: 'PT').render if current_user.enable_pt_session_tracking %>
</header>

app/views/shared/_admin_nav.html.erb
<% if current_user_admin? %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Admin
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <%= link_to 'Users', admin_users_path, class: 'dropdown-item' %>
    </div>
  </li>
<% end %>

app/views/shared/_datetime_picker.html.erb
<%= form.label 'When', class: 'required' %><br>
<%= form.datetime_select :occurred_at, ampm: true, minute_step: 5, value: Date.today, required: true, class: 'form-control' %>

app/views/shared/_delete_footer.html.erb
<details>
  <summary class='mt-4 border-top border-secondary'><h5 class="inline-block pt-3">Danger Zone</h5></summary>
  <footer>
    <p>Deleting this <%= object.class.name %> cannot be undone.
      <%= link_to "Click to delete #{object.class.name}", delete_path, data: { turbo_method: :delete, turbo_confirm: local_assigns[:message] ? message : 'Are you sure? This action cannot be undone.' }, class: "text-danger" %>.
    </p>
  </footer>
</details>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this form from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_filter_form.html.erb
<%= form_tag(destination_path, method: 'get', id: 'filter-form' ) do %>
  <div class='row'>
    <div class='col-4'>
      <%= select_tag :body_part_id,
      options_for_select(body_parts.by_name.map { |bp| [bp.name, bp.id] }, params[:body_part_id]),
      include_blank: 'All Body Parts',
      class: 'form-control'
      %>
    </div>

    <div class='col-4'>
      <%= select_tag :timeframe,
      options_for_select(Report::TIMEFRAMES, params[:timeframe]),
      include_blank: 'All Time',
      class: 'form-control'
      %>
    </div>

    <div class='col-2'>
      <button type='submit' class='btn btn-success'>Submit</button>
    </div>

    <div class='col-2'>
      <%= link_to 'Reset', destination_path, class: 'btn btn-outline-secondary' %>
    </div>
  </div> <!-- row -->
<% end %>
<hr>

app/views/shared/_flashes.html.erb
<% flash.each do |type, message| %>
  <div class="mt-3 alert alert-<%= bootstrap_flash_class(type) %> alert-dismissible fadein">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <%= link_to MaterialIconComponent.new(icon: 'clinical_notes', title: 'Therapy Tracker', weight: :normal).render, root_url, class: 'navbar-logo' %>
  <%= link_to 'TherapyTracker', root_url, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= render 'shared/admin_nav' %>
      <%= render 'shared/session_nav' %>
    </ul>
  </div>
</nav>

app/views/shared/_quick_log_button_to.html.erb
<%= button_to(MaterialIconComponent.new(
      icon: decorated_log.icon_name,
      size: :large
    ).render + "<br>+#{text}".html_safe,
    path,
    remote: use_js,
    form_class: "w-100", # applies to form
    class: "add-log-button #{decorated_log.css_name}-button" # applies to button
  )%>

app/views/shared/_search_form.html.erb
<%= form_tag(url, method: 'get', id: 'search-form' ) do %>
  <div class="col-xs-12">
    <%= MaterialIconComponent.new(icon: 'search', classes: 'search-icon').render %>
    <%= text_field_tag :search, params[:search], placeholder: 'Search', class: 'form-control form-control-sm' %>
  </div>
<% end %>

<p class='clear-search'><%= link_to 'Clear Search', url %></p>

app/views/shared/_session_nav.html.erb
  <% if current_user %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Log New
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <%= link_to '+ Exercise Log', new_exercise_log_path, class: 'dropdown-item' %>
      <%= link_to '+ Pain Log', new_pain_log_path, class: 'dropdown-item' %>
      <%= link_to '+ PT Session', new_pt_session_log_path, class: 'dropdown-item' if current_user.enable_pt_session_tracking %>
      <%= link_to '+ SLIT Log', new_slit_log_path, class: 'dropdown-item' if current_user.enable_slit_tracking %>
    </div>
  </li>

  <% if current_user.pain_log_quick_form_values.any? %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Quick Log
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <%= button_to 'SLIT dose', quick_log_create_path, method: :post, class: 'dropdown-item' if current_user.enable_slit_tracking? %>
      <%= button_to 'SLIT dose New Bottle', quick_log_create_path, params: {started_new_bottle: true}, method: :post, class: 'dropdown-item' if current_user.enable_slit_tracking? %>
       <% current_user.pain_log_quick_form_values.order(name: :asc).each do |attr| %>
        <%= button_to attr.name, create_pain_log_from_quick_form_path(content: attr), class: 'dropdown-item'  %>
      <% end %>
    </div>
  </li>
  <% end %>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      History
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <%= link_to 'Pain Stats by Body Part', stats_path, class: 'dropdown-item' %>
      <%= link_to 'Charts', charts_path, class: 'dropdown-item' %>
      <%= link_to 'SLIT Logs for Print', new_slit_log_report_path, class: 'dropdown-item' if current_user.enable_slit_tracking %>
      <div class='dropdown-divider'></div>
      <%= link_to 'Exercise Logs', exercise_logs_path, class: 'dropdown-item' %>
      <%= link_to 'Pain Logs', pain_logs_path, class: 'dropdown-item' %>
      <%= link_to 'PT Session Logs', pt_session_logs_path, class: 'dropdown-item' %>
      <%= link_to 'SLIT Logs', slit_logs_path, class: 'dropdown-item' %>
    </div>
  </li>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Manage
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <%= link_to 'Exercises', exercises_path, class: 'dropdown-item' %>
      <%= link_to 'Body Parts', body_parts_path, class: 'dropdown-item' %>
      <%= link_to 'Pains', pains_path, class: 'dropdown-item' %>
      <%= link_to 'Pain "Quick Loging" Defaults', pain_log_quick_form_values_path, class: 'dropdown-item' %>
    </div>
  </li>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.email %>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <%= link_to 'Edit My Settings', edit_user_settings_path, class: 'dropdown-item' %>
      <%= link_to 'Change My Password', edit_user_registration_path, class: 'dropdown-item' %>
      <%= link_to 'Log Out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'dropdown-item' %>
    </div>
  </li>

  <% else %>
  <li class="nav-item">
    <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
  </li>
  <% end %>