config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Clobber sign_up for now so no new users can sign up.
  devise_for :users, path_names: {
    sign_up: ""
  }

  root to: "logs#index"

  namespace :admin do
    resources :users, only: [:index, :show]
  end

  resources :users, only: [:update]
  get "users/settings", action: :edit, controller: "users", as: "edit_user_settings"

  resources :charts, only: [:index]
  resources :stats, only: [:index]

  resources :exercises
  resources :pain_log_quick_form_values, only: [:index, :new, :create, :edit, :update, :destroy]
  post "/create_pain_log_from_quick_form", to: "pain_logs#create_from_quick_form"

  resources :pains, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :body_parts, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :logs, only: [:index]
  resources :exercise_logs
  resources :pain_logs
  resources :pt_session_logs do
    resources :exercise_logs, controller: "pt_session_logs/exercise_logs", only: [:new, :create, :show, :edit, :update, :destroy]
  end

  resources :slit_logs
  post "/quick_log_create", to: "slit_logs#quick_log_create"

  resources :slit_log_reports, only: [:index, :new]
end

app/controllers/exercises_controller.rb
# frozen_string_literal: true

class ExercisesController < ApplicationController
  before_action :set_exercise, only: %i[show edit update destroy]
  before_action :authorize_exercise, only: %i[show edit update destroy]

  def index
    @exercises = current_user.exercises.search(params[:search]).by_name
  end

  def show
    respond_to do |format|
      format.html { render json: @exercise, status: :ok }
      format.turbo_stream
    end
  end

  def new
    @exercise = current_user.exercises.new
  end

  def edit
  end

  def create
    @exercise = current_user.exercises.new(exercise_params)

    if @exercise.save
      redirect_to exercises_url
    else
      render :new
    end
  end

  def update
    if @exercise.update(exercise_params)
      redirect_to exercises_url, notice: "Exercise was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: "Exercise was successfully destroyed." }
    end
  end

  private

  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  def authorize_exercise
    redirect_to root_path, alert: authorization_alert unless authorized_user?(@exercise)
  end

  def exercise_params
    params.require(:exercise)
      .permit(:user_id, :name, :default_sets, :default_reps, :default_rep_length, :default_resistance, :description, :default_per_side)
  end
end

app/views/exercises/_form.html.erb
<%= form_with(model: exercise) do |form| %>
  <%= render partial: 'shared/errors', locals: {object: exercise} %>

  <div class="field">
    <%= form.label :name, class: 'required' %>
    <%= form.text_field :name, required: true, class: 'form-control' %>
  </div>

  <div class="row">
    <div class="col">
      <div class="field">
        <%= form.label :default_sets, class: 'required' %>
        <%= form.number_field :default_sets, required: true, class: 'form-control' %>
      </div>
    </div>
    <div class="col">
      <div class="field">
        <%= form.label :default_reps, class: 'required' %>
        <%= form.number_field :default_reps, required: true, class: 'form-control' %>
      </div>
    </div>
    <div class="col">
      <div class="field">
        <%= form.label :default_rep_length, class: 'required' %>
        <%= form.number_field :default_rep_length, placeholder: 'seconds', required: true, class: 'form-control' %>
      </div>
    </div>
    <div class="col">
      <div class="field">
        <%= form.label 'Per Side?' %>
        <%= form.check_box :default_per_side, class: 'form-control' %>
      </div>
    </div>
  </div> <!-- row -->

  <div class="field">
    <%= form.label 'Default Resistance Level' %>
    <%= form.text_field :default_resistance, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description, class: 'required' %>
    <%= form.text_area :description, required: true, class: 'form-control' %>
  </div>

  <div class="mt-3 mb-3">
    <%= form.submit class: button_class('success') %>
    <%= link_to 'Cancel', exercises_path, class: button_class('secondary') %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing Exercise</h1>

<%= render 'form', exercise: @exercise %>

<%= render partial: 'shared/delete_footer', locals: { object: @exercise, delete_path: @exercise, message: 'If you delete this exercise, you will also delete any Exercise Logs you created for it. Are you sure you want to do this? It cannot be undone.' } %>

app/views/exercises/index.html.erb
<%= link_to 'New Exercise', new_exercise_path, class: button_class('primary pull-right') %>

<h1>Exercises</h1>

<% if current_user.exercises.any? %>
  <%= render partial: 'shared/search_form', locals: { url: exercises_path } %>

  <section>
    <% @exercises.each do |exercise| %>
      <details class='index-list-item'>
        <summary><%= link_to exercise.name, edit_exercise_path(exercise) %></summary>
        <p class='exercise-description'><strong><%= exercise.default_sets %> sets of <%= exercise.default_reps %> with <%= exercise.default_rep_length %> sec hold <%= 'per side' if exercise.default_per_side %></strong><br>
          <%= exercise.description %>
        </p>
      </details>
    <% end %>
  </section>

<% else %>
  <p>Create a New Exercise</p>
  <%= link_to 'New Exercise', new_exercise_path, class: button_class('primary btn-wide') %>
<% end %>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= render 'form', exercise: @exercise %>

app/views/exercises/show.turbo_stream.erb
<!-- Exercise data fields to update when exercise dropdown is changed: -->

<%= turbo_stream.replace "exercise_log_sets" do %>
  <%= tag.input type: "number",
      required: "required",
      value: @exercise.default_sets,
      name: "exercise_log[sets]",
      id: "exercise_log_sets",
      class: "form-control" %>
<% end %>

<%= turbo_stream.replace "exercise_log_reps" do %>
  <%= tag.input type: "number", 
      required: "required",
      value: @exercise.default_reps,
      name: "exercise_log[reps]",
      id: "exercise_log_reps",
      class: "form-control" %>
<% end %>

<%= turbo_stream.replace "exercise_log_rep_length" do %>
  <%= tag.input type: "number", 
      required: "required",
      value: @exercise.default_rep_length,
      name: "exercise_log[rep_length]",
      id: "exercise_log_rep_length",
      class: "form-control" %>
<% end %>

<%= turbo_stream.replace "exercise_log_per_side" do %>
  <input name="exercise_log[per_side]" type="hidden" value="0" autocomplete="off">
  <%= tag.input type: "checkbox", 
      value: "1", 
      checked: @exercise.default_per_side,
      name: "exercise_log[per_side]", 
      id: "exercise_log_per_side",
      class: "form-control" %>
<% end %>

<%= turbo_stream.replace "exercise_log_resistance" do %>
  <%= tag.input type: "text",
      value: @exercise.default_resistance,
      name: "exercise_log[resistance]",
      id: "exercise_log_resistance",
      class: "form-control" %>
<% end %>